### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by bfpimentel** [bfpimentel/chuck-norris-app#1]
# Feature Roadmap

### First steps
- [x] Project Creation [feature/project-creation](https://github.com/bfpimentel/chuck-norris-app/tree/feature/project-creation)
- [x] Feature Roadmap
### Actions
[feature/github-action-pr-script](https://github.com/bfpimentel/chuck-norris-app/tree/feature/github-action-pr-script)
- [x] Code coverage (codecov.io)
- [x] Static code analysis
- [x] Generate APK and Upload [feature/generate-apk-ci-script](https://github.com/bfpimentel/chuck-norris-app/tree/feature/generate-apk-ci-script)
### Readme 
[feature/readme-part-1](https://github.com/bfpimentel/chuck-norris-app/tree/feature/readme-part-1)
[feature/readme-part-2](https://github.com/bfpimentel/chuck-norris-app/tree/feature/readme-part-2)
[feature/readme-part-3](https://github.com/bfpimentel/chuck-norris-app/tree/feature/readme-part-3)
- [x] Introduction
- [x] Setup instructions
- [x] Architecture description
- [x] Project screens and explanation

### APIs
[feature/add-dependencies](https://github.com/bfpimentel/chuck-norris-app/tree/feature/add-dependencies)
- [x] Koin
- [x] RxJava
- [x] Retrofit
- [x] Jetpack Navigation
- [x] Jacoco
- [x] Detekt
- [x] JUnit5 [feature/github-action-pr-script](https://github.com/bfpimentel/chuck-norris-app/tree/feature/github-action-pr-script)
- [x] Room [feature/room-db](https://github.com/bfpimentel/chuck-norris-app/tree/feature/room-db)
### Abstractions
- [x] Fragment [feature/fragment-abstraction](https://github.com/bfpimentel/chuck-norris-app/tree/feature/fragment-abstraction)
- [x] UseCase [feature/use-case-abstraction](https://github.com/bfpimentel/chuck-norris-app/tree/feature/use-case-abstraction)
- [x] ViewModel [feature/view-model-abstraction](https://github.com/bfpimentel/chuck-norris-app/tree/feature/view-model-abstraction)
### Misc
- [x] Modular presentation and data layers [feature/modularity](https://github.com/bfpimentel/chuck-norris-app/tree/feature/modularity)
- [x] Scheduler Provider [feature/scheduler-provider](https://github.com/bfpimentel/chuck-norris-app/tree/feature/scheduler-provider)
- [x] Error handling [feature/error-handling](https://github.com/bfpimentel/chuck-norris-app/tree/feature/error-handling) refactored at: [feature/error-handling-refactor](https://github.com/bfpimentel/chuck-norris-app/tree/feature/error-handling-refactor)
- [x] Networking [feature/networking](https://github.com/bfpimentel/chuck-norris-app/tree/feature/networking)
- [x] Main Activity [feature/main-activity](https://github.com/bfpimentel/chuck-norris-app/tree/feature/main-activity)
- [x] Dependency Injection [feature/dependency-injection](https://github.com/bfpimentel/chuck-norris-app/tree/feature/dependency-injection)
- [x] Navigator [feature/navigator](https://github.com/bfpimentel/chuck-norris-app/tree/feature/navigator)
- [x] App Icon [feature/app-icon](https://github.com/bfpimentel/chuck-norris-app/tree/feature/app-icon)

### First Access
- [x] Show search indicator [feature/first-access-search-indicator](https://github.com/bfpimentel/chuck-norris-app/tree/feature/first-access-search-indicator)
### Listing
[feature/list-facts-integration](https://github.com/bfpimentel/chuck-norris-app/tree/feature/list-facts-integration)
[feature/list-facts-front](https://github.com/bfpimentel/chuck-norris-app/tree/feature/list-facts-front)
- [x] Description
- [x] Different font sizes
- [x] Category
- [x] Share
- [x] Empty list

### Get Suggestions 
[feature/search-get-suggestions](https://github.com/bfpimentel/chuck-norris-app/tree/feature/search-get-suggestions)
- [x] Save offline after getting from server for the first time
- [x] Get 8 of them randomly after saving them
### Search facts manually
[feature/search-manually-integration](https://github.com/bfpimentel/chuck-norris-app/tree/feature/search-manually-integration)
[feature/search-manually-front](https://github.com/bfpimentel/chuck-norris-app/tree/feature/search-manually-front)
- [x] Save after search, can't repeat
- [x] List 10 past searches, most recent -> older
- [x] Prevent emojis and other special characters
